package aslan.can.iteminventory.dao;

import java.util.List;
import java.util.Optional;
import java.util.UUID;
import aslan.can.iteminventory.model.Item;
import aslan.can.iteminventory.model.User;
import org.springframework.stereotype.Repository;
import java.sql.*;

@Repository("oracle-item")
public class OracleDBItemDao implements ItemDao {

    public static Connection dbConnection;

    public static void establishConnection() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            dbConnection = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521/xepdb1",
                AppProperties.OracleUsername,
                AppProperties.OraclePassword);
            
            try {
                PreparedStatement tableAccessStatement = dbConnection.prepareStatement(
                    "SELECT * FROM items");
                tableAccessStatement.executeQuery();
            }
            catch (SQLSyntaxErrorException e) {
                e.printStackTrace();
                PreparedStatement createTableStatement = dbConnection.prepareStatement(
                    "CREATE TABLE users(task_id NUMBER GENERATED BY DEFAULT AS IDENTITY, task_uuid VARCHAR2(63), owner_uuid VARCHAR2(63), title VARCHAR2(63), desc VARCHAR2(255), category NUMBER, PRIMARY KEY(task_id))");
                    createTableStatement.executeQuery();
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public int insertItem(User owner, Item item) {
        // TODO Auto-generated method stub
        return 0;
    }

    @Override
    public List<Item> getAllItems() {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public Optional<Item> selectItemByID(UUID itemID) {
        // TODO Auto-generated method stub
        return Optional.empty();
    }

    @Override
    public int deleteItemByID(UUID itemID) {
        // TODO Auto-generated method stub
        return 0;
    }

    @Override
    public int updateItemByID(UUID itemID, Item newItem) {
        // TODO Auto-generated method stub
        return 0;
    }
    
}
