package aslan.can.iteminventory.dao;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import aslan.can.iteminventory.model.Item;
import org.springframework.stereotype.Repository;
import java.sql.*;

@Repository("oracle-item")
public class OracleDBItemDao implements ItemDao {

    public static Connection dbConnection;

    public static void establishConnection() {
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            dbConnection = DriverManager.getConnection(
                AppProperties.OracleLink,
                AppProperties.OracleUsername,
                AppProperties.OraclePassword);

            // PreparedStatement del = dbConnection.prepareStatement(
            //     "DROP TABLE items");
            // del.executeQuery();

            try {
                PreparedStatement tableAccessStatement = dbConnection.prepareStatement(
                    "SELECT * FROM items");
                tableAccessStatement.executeQuery();
            }
            catch (SQLSyntaxErrorException e) {
                e.printStackTrace();
                PreparedStatement createTableStatement = dbConnection.prepareStatement(
                    "CREATE TABLE items(task_id NUMBER GENERATED BY DEFAULT AS IDENTITY, task_uuid VARCHAR2(63), owner_uuid VARCHAR2(63), task_title VARCHAR2(63), task_desc VARCHAR2(255), task_category VARCHAR2(63), PRIMARY KEY(task_id))");
                    createTableStatement.executeQuery();
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public int insertItem(UUID ownerUUID, Item item) {
        try {
            PreparedStatement insertStatement = dbConnection.prepareStatement(
                "INSERT INTO items(task_uuid, owner_uuid, task_title, task_desc, task_category) VALUES('"
                + item.getTaskUUID() + "', '"
                + ownerUUID + "', '"
                + item.getTitle() + "', '"
                + item.getDesc() + "', '"
                + item.getCategory() + "')");
            insertStatement.executeQuery();
            insertItemDebug(item.getTaskUUID(), ownerUUID, item.getTitle(), item.getDesc(), item.getCategory());
            return 1;
        }
        catch (Exception e) {
            e.printStackTrace();
            return 0;
        }
    }

    @Override
    public List<Item> getAllItems() {
        ArrayList<Item> allItems = new ArrayList<Item>();

        try {
            PreparedStatement getAllItemsStatement = dbConnection.prepareStatement(
                "SELECT * FROM items");
            ResultSet result = getAllItemsStatement.executeQuery();

            while ( result.next() ) {
                allItems.add(new Item(  UUID.fromString(result.getString(2)),
                                        UUID.fromString(result.getString(3)),
                                        result.getString(4),
                                        result.getString(5),
                                        result.getString(6)));
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }

        return allItems;
    }

    @Override
    public List<Item> getItemsOfUserByID(UUID userUUID) {
        ArrayList<Item> allItems = new ArrayList<Item>();

        try {
            PreparedStatement getAllItemsStatement = dbConnection.prepareStatement(
                "SELECT * FROM items WHERE items.owner_uuid = '" + userUUID + "'");
            ResultSet result = getAllItemsStatement.executeQuery();

            while ( result.next() ) {
                allItems.add(new Item(  UUID.fromString(result.getString(2)),
                                        UUID.fromString(result.getString(3)),
                                        result.getString(4),
                                        result.getString(5),
                                        result.getString(6)));
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }

        if (allItems.isEmpty()) {
            allItems.add(new Item("userHasNoItemsError"));
        }

        return allItems;
    }

    @Override
    public int deleteItemByID(UUID itemID) {
        try {
            PreparedStatement deleteStatement = dbConnection.prepareStatement(
                "DELETE FROM items WHERE items.task_uuid='" + itemID + "'");
            deleteStatement.executeQuery();
            System.out.println("Deleted item with task UUID " + itemID + " if it exists in the database.");
            return 1;
        }
        catch (Exception e) {
            e.printStackTrace();
            return 0;
        }
    }
    
    private void insertItemDebug(UUID taskUUID, UUID ownerUUID, String title, String desc, String category) {
        System.out.println("------ITEM ADDED-------");
        System.out.println("TaskUUID: " + taskUUID);
        System.out.println("OwnerUUID: " + ownerUUID);
        System.out.println("Title: " + title);
        System.out.println("Description: " + desc);
        System.out.println("Category: " + category.toLowerCase());
        System.out.println("------ITEM ADDED-------");
    }
}
